routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\MainController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'Admin'], function () {
    Route::get('/', 'Backend\MainController@index')->name('admin.main');

    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('role', 'Backend\RoleController');
        Route::resource('permission', 'Backend\PermissionController');
        Route::resource('user', 'Backend\UserController');
			});
		});
		
Route::resource('category', 'Backend\CategoryController');
Route::resource('product', 'Backend\ProductController');	
Route::resource('pos', 'Backend\PosController');
Route::get('pos-list', 'Backend\PosController@list')->name('pos.list');

// Route::get('pos/cart', 'Backend\CartController@getCart')->name('cart.getCart');
Route::post('pos/cart', 'Backend\CartController@getCart')->name('cart.getCart');
Route::post('pos/addToCart', 'Backend\CartController@add')->name('cart.addToCart');
Route::post('pos/updateQtyCart', 'Backend\CartController@updateQty')->name('cart.updateQtyCart');
Route::post('pos/deleteItem', 'Backend\CartController@deleteItem')->name('cart.deleteItem');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use SoftDeletes;

	protected $fillable = [
		'name'
	];

	public function product()
	{
		return $this->hasMany('App\Product');
	}
}

app/Http/Controllers/Backend/CartController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use Cart;

class CartController extends Controller
{
    public function add(Request $request)
		{
			try {
				$product = Product::findOrFail($request->id);

				Cart::session(auth()->user()->id)->add([
					'id' => $request->id,
					'name' => $request->name,
					'price' => $request->price,
					'quantity' => $request->qty,
					'associatedModel' => $product
				]);

				$data = [
					'message' => 'Berhasil Memasukan Kedalam Keranjang'
				];

				return response()->json($data, 200);
			} catch (\Exception $e) {
				$data = [
					'code' => '404',
					'message' => 'Product Salah !',
					'error' => $e
				];
				return response()->json($data, 500);
			}
		}

		public function getCart(Request $request)
		{
			$cart = Cart::session($request->userId)->getContent();
			$data = [
				'cart' => $cart,
				'totalItem' => $cart->count(),
				'totalQty' => Cart::session(auth()->user()->id)->getTotalQuantity(),
				'totalPay' => Cart::session(auth()->user()->id)->getTotal()
			];
			return response()->json($data, 200);
		}

		public function updateQty(Request $request)
		{
			$cart = Cart::session(auth()->user()->id)->update($request->id, [
				'quantity' => [
					'relative' => false,
					'value' => $request->qty
				]
			]);
			
			$data = [
				'message' => 'Berhasil Mengubah Qty Produk !'
			];
			return response()->json($data, 200);
		}

		public function deleteItem(Request $request)
		{
			$cart = Cart::session(auth()->user()->id)->remove($request->id);
			$data = [
				'message' => 'Berhasil Menghapus Item !'
			];
			return response()->json($data, 200);
		}
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DataTables;
use Illuminate\Support\Facades\Crypt;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
				if($request->ajax()) {
					$data = Category::get();
					return DataTables::of($data)
						->addIndexColumn()
						->addColumn('action', function($data) {
							return '
							<form action="'.route('category.destroy', Crypt::encrypt($data->id)).'" method="post">
								<a href="'.route('category.edit', Crypt::encrypt($data->id)).'" class="btn btn-warning btn-sm">
									<i class="fa fa-edit"></i>
								</a>

								<input type="hidden" name="_token" value="'.csrf_token().'">
								<input type="hidden" name="_method" value="DELETE" >
								<button class="btn btn-danger btn-sm">
									<i class="fa fa-trash"></i>
								</button>	
							</form>
							';
						})
						->rawColumns(['action'])
						->make(true);
				}
			
        return view('backend.category.index');
    }
		
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
					'name' => 'required|string|unique:categories,name'
				]);

				try {
					$category = Category::firstOrCreate([
						'name' => $request->name
					]);

					session()->flash('success', 'Data Kategori di-Tambahkan !');
					return redirect(route('category.index'));
				} catch (\Exception $e) {
					dd($e);
					session()->flash('error', 'Mohon Maaf Terjadi Kesalahan !');
					return redirect()->back();
				}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
				$id = $this->cry($id);
				try {
					$edit = Category::findOrFail($id);

					return view('backend.category.index', compact('edit'));
				} catch (\Exception $e) {
					return redirect()->back();
				}
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
				$this->validate($request, [
					'name' => 'required|string|unique:categories,name'
				]);

				$id = $this->cry($id);
				try {
					$category = Category::findOrFail($id);
					$category->update([
						'name' => $request->name
					]);
					session()->flash('success', 'Berhasil Mengubah Data Kategori !');
					return redirect(route('category.index'));
				} catch (\Exception $e) {
					return redirect()->back();
				}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
				$id = $this->cry($id);
				try {
					$category = Category::findOrFail($id);
					$category->delete();
					session()->flash('success', 'Data Kategori di-Hapus');
					return redirect(route('category.index'));
				} catch (\Exception $e) {
					dd($e);
				}
		}
		
		public function cry($id)
		{
			try {
				$decrypted = Crypt::decrypt($id);
				return $decrypted;
			} catch (Illuminate\Contracts\Encryption\DecryptException $e) {
				dd($e);
			}
		}

}

app/Http/Controllers/Backend/MainController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class MainController extends Controller
{
    public function index()
    {
        return view('backend.main');
    }
}

app/Http/Controllers/Backend/PosController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use App\SellDetail;
use App\SellHeader;
use Cart;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class PosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
				if ($request->ajax()) {
					$product = Product::with('category')->where('name', 'like', '%'.$request->search.'%')->get();
					if (empty($product)) {
						$data = [
							'message' => 'Tidak Di-Temukan Data Produk !',
						];
						return response()->json($data, 200);
					} else {
						return response()->json($product, 200);
					}
				}

				$product = Product::with('category')->get();
        return view('backend.pos.index', compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
				// 
		}

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
			$user = Auth::user();
			if (Cart::session($user->id)->isEmpty()) {
				$data = [
					'code' => '400', 
					'message' => 'Silahkan Pilih Produk untuk Transaksi',
				];
				return response()->json($data, 200);
			} else {
				$cart = Cart::session($user->id)->getContent();	

				DB::beginTransaction();
				try {
					$header = DB::table('sell_headers')->insert([
						'invoice' => 'SL'.time(),
						'user_id' => $user->id,
						'discount' => $request->discount,
						'cash' => $request->cash,
						'total' => Cart::session($user->id)->getTotal(),
						'created_at' => date('Y-m-d H:i:s'),
						'updated_at' => date('Y-m-d H:i:s'),
					]);

					$header_id = DB::getPdo()->lastInsertId();

					foreach ($cart as $item) {
						$detail = DB::table('sell_details')->insert([
							'sell_header_id' => $header_id,
							'product_id' => $item->id,
							'qty' => $item->quantity,
							'price' => $item->price,
							'created_at' => date('Y-m-d H:i:s'),
							'updated_at' => date('Y-m-d H:i:s'),
						]);
					}

					DB::commit();

					$clearCart = Cart::session($user->id)->clear();

					$data = [
						'code' => '200',
						'message' => 'Transaksi Selesai !'
					];

					return response()->json($data, 200);

				} catch (\Exception $e) {
					DB::rollback();
					$data = [
						'code' => '400', 
						'message' => 'Terjadi Kesalahan Saat Menyiman Kedalam Data',
						'error' => $e
					];

					return response()->json($data, 200);
				}
			}

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
		}
		
		public function list(Request $request)
		{
			$sell = SellHeader::orderBy('id', 'DESC')->get();

			return view('backend.pos.list', compact('sell'));
		}
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use DataTables;
use Illuminate\Support\Facades\Crypt;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
				if ($request->ajax()) {
					$data = Product::with('category')->get();
					return DataTables::of($data)
						->addIndexColumn()
						->addColumn('action', function($data) {
							return '
							<form action="'.route('category.destroy', Crypt::encrypt($data->id)).'" method="post">
								<a href="'.route('category.edit', Crypt::encrypt($data->id)).'" class="btn btn-warning btn-sm">
									<i class="fa fa-edit"></i>
								</a>

								<input type="hidden" name="_token" value="'.csrf_token().'">
								<input type="hidden" name="_method" value="DELETE" >
								<button class="btn btn-danger btn-sm">
									<i class="fa fa-trash"></i>
								</button>	
							</form>
							';
						})
						->addColumn('price', function($data) {
							return "Rp. ".number_format($data->price, 0, ',', '.');
						})
						->rawColumns(['action'])
						->make(true);
				}

        return view('backend.product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
				if ($request->ajax()) {
					$a = $request->ajax();
					return response()->json($a, 200);
				}

				$category = Category::orderBy('name')->get();

        return view('backend.product.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/RoleController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    public function index()
    {
        $role = Role::orderBy('id', 'ASC')->get();
        return view('backend.role.index', compact('role'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50'
        ]);

        try {
            $role = Role::firstOrCreate([
                'name' => $request->name
            ]);

            session()->flash('success', 'Data Role di-Tambahkan!');
            return redirect(route('role.index'));
        } catch (\Exception $e) {
            session()->flash('error', 'Terjadi Kesalahan !');
            return redirect()->back();
        }
    }

    public function destroy($id)
    {
        try {
            $role = Role::findOrFail($id);
            $role->delete();
            session()->flash('success', 'Data Role di-Hapus!');
            return redirect(route('role.index'));
        } catch (\Exception $e) {
            session()->flash('error', 'Terjadi Kesalahan! Error');
            return redirect()->back();
        }
    }
}

resources/views/backend/category/index.blade.php
@extends('backend.app')

@section('content')
<div class="col-md-12" style="margin-top: 20px;">
	<div class="col-md-6" style="padding: 0;">
		<div class="portlet light bordered" style="border-radius: 0px;">
			<div class="portlet-title">
				<div class="col-md-12" style="padding: 0px;">
					<h4>Management Kategori</h4>
				</div>
			</div>
			<div class="portlet-body">
				<div class="table-responsive">
					<table class="table table-hover data-table">
						<thead>
							<tr>
								<th width="50px">#</th>
								<th>Nama Kategori</th>
								<th width="100px">Aksi</th>
							</tr>
						</thead>
						<tbody>
	
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')
<!-- jQuery -->
<script src="{{ asset('') }}plugins/jquery/jquery.min.js"></script>
<script>
	$(document).ready(function() {
		var table = $('.data-table').DataTable({
			processing: true,
			serverSide: true,
			ajax: "{{ route('category.index') }}",
			columns: [
				{
					data: 'DT_RowIndex',
					name: 'DT_RowIndex'
				},
				{
					data: 'name',
					name: 'name',
				},
				{
					data: 'action',
					name: 'action',
					orderable: false,
					searchable: false
				}
			]
		});
	
	});
</script>

resources/views/backend/category/index1.blade.php
@extends('backend.layout.master')

@section('judul')
		Management Kategori Produk
@endsection

@section('content')
<div class="col-5 col-md-5">
	<div class="card card-dark">
		<div class="card-header">
			<h4 class="card-title">
				Form Kategori
			</h4>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-12">
					@if (isset($edit))
						<form action="{{ route('category.update', Crypt::encrypt($edit->id)) }}" method="post">
							@method('PUT')
					@else
						<form action="{{ route('category.store') }}" method="post">
					@endif
						@csrf
						<div class="form-group">
							<label for="">Nama Kategori :</label>
							<input type="text" name="name" id="name" class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" value="{{ isset($edit) ? $edit->name:old('name') }}" required>
							<p class="text-danger text-sm">
								{{ $errors->first('name') }}
							</p>
						</div>
						<div class="form-group">
							<div class="row">
								@if (isset($edit))
									<div class="col-4">
										<button type="submit" class="btn btn-success btn-sm btn-block btn-flat">
											<i class="fa fa-check"></i> &ensp;
											Simpan
										</button>
									</div>
									<div class="col-4">
										<button type="reset" class="btn btn-warning btn-sm btn-block btn-flat">
											<i class="fa fa-undo"></i>
											Reset
										</button>
									</div>
									<div class="col-4">
										<a href="{{ route('category.index') }}" class="btn btn-danger btn-sm btn-block btn-flat">
											<i class="fa fa-times"></i>
											Cancel
										</a>
									</div>

								@else
									<div class="col-6">
										<button type="submit" class="btn btn-success btn-sm btn-block btn-flat">
											<i class="fa fa-check"></i> &ensp;
											Tambah Data Kategori
										</button>
									</div>
									<div class="col-6">
										<button type="reset" class="btn btn-danger btn-sm btn-block btn-flat">
											<i class="fa fa-undo"></i>
											Reset Input
										</button>
									</div>
								@endif
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-12 col-md-12">
	<div class="card card-dark">
		<div class="card-header">
			<h4 class="card-title">
				Data Kategori
			</h4>
		</div>
		<div class="card-body">
			<div class="col-md-12">
				<div class="table-responsive">
					<table class="table table-hover data-table">
						<thead>
							<tr>
								<th width="50px">#</th>
								<th>Nama Kategori</th>
								<th width="100px">Aksi</th>
							</tr>
						</thead>
						<tbody>
	
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
		
<script>
	$(document).ready(function() {
	
		var table = $('.data-table').DataTable({
			processing: true,
			serverSide: true,
			ajax: "{{ route('category.index') }}",
			columns: [
				{
					data: 'DT_RowIndex',
					name: 'DT_RowIndex'
				},
				{
					data: 'name',
					name: 'name',
				},
				{
					data: 'action',
					name: 'action',
					orderable: false,
					searchable: false
				}
			]
		});
	
	});
</script>
@endsection