routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\MainController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'Admin'], function () {
    Route::get('/', 'Backend\MainController@index')->name('admin.main');

    Route::group(['middleware' => ['role:Admin']], function () {
        Route::resource('role', 'Backend\RoleController');
        Route::resource('permission', 'Backend\PermissionController');
        Route::resource('user', 'Backend\UserController');
			});
		});
		
Route::resource('category', 'Backend\CategoryController');
Route::resource('product', 'Backend\ProductController');	
Route::resource('pos', 'Backend\PosController');
Route::get('pos-list', 'Backend\PosController@list')->name('pos.list');

// Route::get('pos/cart', 'Backend\CartController@getCart')->name('cart.getCart');
Route::post('pos/cart', 'Backend\CartController@getCart')->name('cart.getCart');
Route::post('pos/addToCart', 'Backend\CartController@add')->name('cart.addToCart');
Route::post('pos/updateQtyCart', 'Backend\CartController@updateQty')->name('cart.updateQtyCart');
Route::post('pos/deleteItem', 'Backend\CartController@deleteItem')->name('cart.deleteItem');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
		];
		
		public function sell()
		{
			return $this->hasMany('App\SellHeader');
		}
}

app/Http/Controllers/Backend/CartController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use Cart;

class CartController extends Controller
{
    public function add(Request $request)
		{
			try {
				$product = Product::findOrFail($request->id);

				Cart::session(auth()->user()->id)->add([
					'id' => $request->id,
					'name' => $request->name,
					'price' => $request->price,
					'quantity' => $request->qty,
					'associatedModel' => $product
				]);

				$data = [
					'message' => 'Berhasil Memasukan Kedalam Keranjang'
				];

				return response()->json($data, 200);
			} catch (\Exception $e) {
				$data = [
					'code' => '404',
					'message' => 'Product Salah !',
					'error' => $e
				];
				return response()->json($data, 500);
			}
		}

		public function getCart(Request $request)
		{
			$cart = Cart::session($request->userId)->getContent();
			$data = [
				'cart' => $cart,
				'totalItem' => $cart->count(),
				'totalQty' => Cart::session(auth()->user()->id)->getTotalQuantity(),
				'totalPay' => Cart::session(auth()->user()->id)->getTotal()
			];
			return response()->json($data, 200);
		}

		public function updateQty(Request $request)
		{
			$cart = Cart::session(auth()->user()->id)->update($request->id, [
				'quantity' => [
					'relative' => false,
					'value' => $request->qty
				]
			]);
			
			$data = [
				'message' => 'Berhasil Mengubah Qty Produk !'
			];
			return response()->json($data, 200);
		}

		public function deleteItem(Request $request)
		{
			$cart = Cart::session(auth()->user()->id)->remove($request->id);
			$data = [
				'message' => 'Berhasil Menghapus Item !'
			];
			return response()->json($data, 200);
		}
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DataTables;
use Illuminate\Support\Facades\Crypt;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
				if($request->ajax()) {
					$data = Category::get();
					return DataTables::of($data)
						->addIndexColumn()
						->addColumn('action', function($data) {
							return '
							<form action="'.route('category.destroy', Crypt::encrypt($data->id)).'" method="post">
								<a href="'.route('category.edit', Crypt::encrypt($data->id)).'" class="btn btn-warning btn-sm">
									<i class="fa fa-edit"></i>
								</a>

								<input type="hidden" name="_token" value="'.csrf_token().'">
								<input type="hidden" name="_method" value="DELETE" >
								<button class="btn btn-danger btn-sm">
									<i class="fa fa-trash"></i>
								</button>	
							</form>
							';
						})
						->rawColumns(['action'])
						->make(true);
				}
			
        return view('backend.category.index');
    }
		
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
					'name' => 'required|string|unique:categories,name'
				]);

				try {
					$category = Category::firstOrCreate([
						'name' => $request->name
					]);

					session()->flash('success', 'Data Kategori di-Tambahkan !');
					return redirect(route('category.index'));
				} catch (\Exception $e) {
					dd($e);
					session()->flash('error', 'Mohon Maaf Terjadi Kesalahan !');
					return redirect()->back();
				}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
				$id = $this->cry($id);
				try {
					$edit = Category::findOrFail($id);

					return view('backend.category.index', compact('edit'));
				} catch (\Exception $e) {
					return redirect()->back();
				}
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
				$this->validate($request, [
					'name' => 'required|string|unique:categories,name'
				]);

				$id = $this->cry($id);
				try {
					$category = Category::findOrFail($id);
					$category->update([
						'name' => $request->name
					]);
					session()->flash('success', 'Berhasil Mengubah Data Kategori !');
					return redirect(route('category.index'));
				} catch (\Exception $e) {
					return redirect()->back();
				}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
				$id = $this->cry($id);
				try {
					$category = Category::findOrFail($id);
					$category->delete();
					session()->flash('success', 'Data Kategori di-Hapus');
					return redirect(route('category.index'));
				} catch (\Exception $e) {
					dd($e);
				}
		}
		
		public function cry($id)
		{
			try {
				$decrypted = Crypt::decrypt($id);
				return $decrypted;
			} catch (Illuminate\Contracts\Encryption\DecryptException $e) {
				dd($e);
			}
		}

}

app/Http/Controllers/Backend/MainController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class MainController extends Controller
{
    public function index()
    {
        return view('backend.main');
    }
}

app/Http/Controllers/Backend/PosController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use App\SellDetail;
use App\SellHeader;
use Cart;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class PosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
				if ($request->ajax()) {
					$product = Product::with('category')->where('name', 'like', '%'.$request->search.'%')->get();
					if (empty($product)) {
						$data = [
							'message' => 'Tidak Di-Temukan Data Produk !',
						];
						return response()->json($data, 200);
					} else {
						return response()->json($product, 200);
					}
				}

				$product = Product::with('category')->get();
        return view('backend.pos.index', compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
				// 
		}

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
			$user = Auth::user();
			if (Cart::session($user->id)->isEmpty()) {
				$data = [
					'code' => '400', 
					'message' => 'Silahkan Pilih Produk untuk Transaksi',
				];
				return response()->json($data, 200);
			} else {
				$cart = Cart::session($user->id)->getContent();	

				DB::beginTransaction();
				try {
					$header = DB::table('sell_headers')->insert([
						'invoice' => 'SL'.time(),
						'user_id' => $user->id,
						'discount' => $request->discount,
						'cash' => $request->cash,
						'total' => Cart::session($user->id)->getTotal(),
						'created_at' => date('Y-m-d H:i:s'),
						'updated_at' => date('Y-m-d H:i:s'),
					]);

					$header_id = DB::getPdo()->lastInsertId();

					foreach ($cart as $item) {
						$detail = DB::table('sell_details')->insert([
							'sell_header_id' => $header_id,
							'product_id' => $item->id,
							'qty' => $item->quantity,
							'price' => $item->price,
							'created_at' => date('Y-m-d H:i:s'),
							'updated_at' => date('Y-m-d H:i:s'),
						]);
					}

					DB::commit();

					$clearCart = Cart::session($user->id)->clear();

					$data = [
						'code' => '200',
						'message' => 'Transaksi Selesai !'
					];

					return response()->json($data, 200);

				} catch (\Exception $e) {
					DB::rollback();
					$data = [
						'code' => '400', 
						'message' => 'Terjadi Kesalahan Saat Menyiman Kedalam Data',
						'error' => $e
					];

					return response()->json($data, 200);
				}
			}

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
		}
		
		public function list(Request $request)
		{
			$sell = SellHeader::orderBy('id', 'DESC')->get();

			return view('backend.pos.list', compact('sell'));
		}
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use DataTables;
use Illuminate\Support\Facades\Crypt;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
				if ($request->ajax()) {
					$data = Product::with('category')->get();
					return DataTables::of($data)
						->addIndexColumn()
						->addColumn('action', function($data) {
							return '
							<form action="'.route('category.destroy', Crypt::encrypt($data->id)).'" method="post">
								<a href="'.route('category.edit', Crypt::encrypt($data->id)).'" class="btn btn-warning btn-sm">
									<i class="fa fa-edit"></i>
								</a>

								<input type="hidden" name="_token" value="'.csrf_token().'">
								<input type="hidden" name="_method" value="DELETE" >
								<button class="btn btn-danger btn-sm">
									<i class="fa fa-trash"></i>
								</button>	
							</form>
							';
						})
						->addColumn('price', function($data) {
							return "Rp. ".number_format($data->price, 0, ',', '.');
						})
						->rawColumns(['action'])
						->make(true);
				}

        return view('backend.product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
				if ($request->ajax()) {
					$a = $request->ajax();
					return response()->json($a, 200);
				}

				$category = Category::orderBy('name')->get();

        return view('backend.product.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/RoleController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    public function index()
    {
        $role = Role::orderBy('id', 'ASC')->get();
        return view('backend.role.index', compact('role'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50'
        ]);

        try {
            $role = Role::firstOrCreate([
                'name' => $request->name
            ]);

            session()->flash('success', 'Data Role di-Tambahkan!');
            return redirect(route('role.index'));
        } catch (\Exception $e) {
            session()->flash('error', 'Terjadi Kesalahan !');
            return redirect()->back();
        }
    }

    public function destroy($id)
    {
        try {
            $role = Role::findOrFail($id);
            $role->delete();
            session()->flash('success', 'Data Role di-Hapus!');
            return redirect(route('role.index'));
        } catch (\Exception $e) {
            session()->flash('error', 'Terjadi Kesalahan! Error');
            return redirect()->back();
        }
    }
}

resources/views/backend/user/index.blade.php
@extends('backend.layout.master')

@section('judul', 'Manajemen Pengguna')

@section('content')
<div class="col-md-12">
    <div id="accordion">
        <div class="card card-dark">
            <div class="card-header" id="formInput" data-toggle="collapse" data-target="#formPengguna"
                aria-expanded="true" aria-controls="formPengguna">
                <h5 class="mb-0">
                    Form Pengguna Baru
                </h5>
            </div>
            <div id="formPengguna" class="collapse {{ !empty($errors) ? '':'show' }} {{ isset($edit) ? 'show':'' }}" aria-labelledby="formInput"
                data-parent="#accordion">
                <div class="col-md-12 mt-2">
                    <div class="col-md-12">
                        @if (isset($edit))
                        <form action="{{ route('user.update', Crypt::encrypt($edit->id)) }}" method="post" class="form">
                            @csrf
                            @method('PUT')
                            @else
                            <form action="{{ route('user.store') }}" method="post" class="form">
                                @csrf
                                @endif
                                <form action="{{ route('user.store') }}" method="post" class="form">
                                    <div class="form-group">
                                        <label for="">Nama Pengguna <i class="text-danger">*</i></label>
                                        <input type="text" name="name" id="name"
                                            class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" required
                                            autofocus value="{{ isset($edit) ? $edit->name: old('name') }}">
                                        <p class="text-sm text-danger">{{ $errors->first('name') }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="">E-Mail Pengguna <i class="text-danger">*</i></label>
                                        <input type="text" name="email" id="email"
                                            class="form-control {{ $errors->has('email') ? 'is-invalid':old('email') }}" required
                                            value="{{ isset($edit) ? $edit->email:'' }}" {{ isset($edit) ? 'readonly':'' }}>
                                        <p class="text-sm text-danger">{{ $errors->first('email') }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="">Password <i class="text-danger">*</i></label>
                                        <input type="password" name="password" id="password"
                                            class="form-control {{ $errors->has('password') ? 'is-invalid':'' }}"
                                            {{ !isset($edit) ? 'required':'' }}>
                                        <p class="text-sm text-danger">{{ $errors->first('password') }}</p>
                                        @if (isset($edit))
                                        <p class="text-sm text-danger">
                                            Kosongkan Apabila Tidak Ingin Merubah Password!
                                        </p>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="">Konfirmasi Password <i class="text-danger">*</i></label>
                                        <input type="password" name="password_confirmation" id="password_confirmation"
                                            class="form-control {{ $errors->has('password_confirmation') ? 'is-invalid':'' }}"
                                            {{ !isset($edit) ? 'required':'' }}>
                                        <p class="text-sm text-danger">{{ $errors->first('password_confirmation') }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="">Role <i class="text-danger">*</i></label>
                                        <select name="role" id="role" class="form-control select2" style="width: 100%;"
                                            data-placeholder="Pilih Role Penggguna" required>
                                            {{-- <option value="">Pilih Pengguna</option> --}}
                                            @foreach ($role as $item)
                                            <option value="{{ $item->name }}"
                                                {{ isset($edit) ? $edit->roles->first()->name == $item->name ? 'selected':'' : '' }}>
                                                {{ $item->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <p class="text-danger">Keterangan : * Wajib di-Isi</p>
                                    <div class="form-group">
                                        <div class="text-left">
                                            @if (isset($edit))
                                            <button type="submit" class="btn btn-success">
                                                <i class="fa fa-save"></i>
                                                Simpan Perubahan Data
                                            </button>
                                            &ensp;
                                            <a href="{{ route('user.index') }}" class="btn btn-danger">
                                                <i class="fa fa-times"></i>
                                                Batalkan Mengubah Pengguna
                                            </a>
                                            @else
                                            <button type="submit" class="btn btn-success">
                                                <i class="fa fa-check"></i>
                                                Tambah Pengguna Baru
                                            </button>
                                            &ensp;
                                            <button type="reset" class="btn btn-danger res">
                                                <i class="fa fa-undo"></i>
                                                Reset Input Form
                                            </button>
                                            @endif
                                        </div>
                                    </div>
                                </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="col-md-12">
    <div class="card card-dark">
        <div class="card-header">
            <h4 class="card-title">
                Data Pengguna
            </h4>
            <div class="card-tools">
                @if (!isset($edit))
                <a href="#formPengguna" class="btn btn-sm btn-primary" data-toggle="collapse"
                    data-target="#formPengguna" aria-expanded="true" aria-controls="formPengguna">
                    <i class="fa fa-plus"></i> &ensp;
                    Tambah Data Pengguna
                </a>
                @endif
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dTable1">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama Pengguna</th>
                            <th>E-Mail</th>
                            <th>Role</th>
                            <th>Tanggal Buat</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($user as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->email }}</td>
                            <td>
                                @foreach ($item->getRoleNames() as $item2)
                                <label for="" class="btn {{ $item2 == 'Admin' ? 'btn-success':'btn-info' }} btn-sm">
                                    {{ $item2 }}
                                </label>
                                @endforeach
                            </td>
                            <td>{{ $item->created_at }}</td>
                            <td>
                                <form action="{{ route('user.destroy', Crypt::encrypt($item->id)) }}" method="post">
                                    <a href="{{ route('user.edit', Crypt::encrypt($item->id)) }}"
                                        class="btn btn-warning btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>

                                    @csrf
                                    @method('DELETE')

                                    <button class="btn btn-danger btn-sm"
                                        onclick="return confirm('Yakin Untuk Melakukan Menghapus Data Ini ?')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @empty

                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        //
    })

</script>
@endsection